[theme]
primaryColor = "#f63366"
backgroundColor = "#ffffff"  # White background for main content
secondaryBackgroundColor = "#f2f2f2"  # Light grey for sidebar background
textColor = "#000000"  # Black text for contrast
font = "sans serif"

[server]
enableStaticServing = true
